CREATE TABLE usuario (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL
);

CREATE TABLE teste (
id INT AUTO_INCREMENT PRIMARY KEY,
id_usuario INT NULL,
assunto VARCHAR(255) NOT NULL,
texto TEXT NOT NULL,

CONSTRAINT fk_teste_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
)